In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\ASUS\Downloads\datasets\play_tennis.csv")

In [3]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [4]:
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [6]:
trans=[('ohe1',OneHotEncoder(),['outlook']),('ohe2',OneHotEncoder(),['temp']),('ohe3',OneHotEncoder(),['humidity']),('ohe4',OneHotEncoder(),['wind'])]

In [7]:
df=df.drop(columns=['day'])

In [8]:
df.columns

Index(['outlook', 'temp', 'humidity', 'wind', 'play'], dtype='object')

In [9]:
c_t=ColumnTransformer(transformers=trans,remainder='passthrough')

In [10]:
new_df=c_t.fit_transform(df)

In [11]:
new_df=pd.DataFrame(new_df,columns=c_t.get_feature_names_out())

In [12]:
new_df

,ohe1__outlook_Overcast,ohe1__outlook_Rain,ohe1__outlook_Sunny,ohe2__temp_Cool,ohe2__temp_Hot,ohe2__temp_Mild,ohe3__humidity_High,ohe3__humidity_Normal,ohe4__wind_Strong,ohe4__wind_Weak,remainder__play
0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,No
1,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,No
2,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,Yes
3,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,Yes
4,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,Yes
5,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,No
6,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,Yes
7,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,No
8,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,Yes
9,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,Yes
10,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,Yes
11,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,Yes
12,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,Yes
13,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,No

In [13]:
new_df['remainder__play']=LabelEncoder().fit_transform(new_df['remainder__play'])

In [14]:
new_df

,ohe1__outlook_Overcast,ohe1__outlook_Rain,ohe1__outlook_Sunny,ohe2__temp_Cool,ohe2__temp_Hot,ohe2__temp_Mild,ohe3__humidity_High,ohe3__humidity_Normal,ohe4__wind_Strong,ohe4__wind_Weak,remainder__play
0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0
1,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0
2,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1
3,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1
4,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1
5,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0
6,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1
7,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0
8,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1
9,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1
10,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1
11,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1
12,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1
13,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0

In [15]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [16]:
df['play'].value_counts()

Yes    9
No     5
Name: play, dtype: int64

In [17]:
p_y=9/14
p_n=5/14

In [18]:
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [19]:
p_n_oo=0
p_n_or=2/5
p_n_os=3/5

p_y_oo=4/9
p_y_or=3/9
p_y_os=2/9

In [20]:
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [21]:
p_y_tc=3/9
p_y_th=2/9
p_y_tm=4/9

p_n_tc=1/5
p_n_th=2/5
p_n_tm=2/5

In [22]:
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [23]:
p_y_hh=3/9
p_y_hn=6/9

p_n_hh=4/5
p_n_hn=1/5

In [24]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [25]:
p_y_ws=3/9
p_y_ww=6/9

p_n_ws=3/5
p_n_ww=2/5

In [26]:
#Outlook=Sunny, Wind='Weak', Humidity='High', Temperature='Hot'

In [27]:
p_yes=p_y*p_y_os*p_y_ww*p_y_hh*p_y_th

In [28]:
p_no=p_n*p_n_os*p_n_ww*p_n_hh*p_n_th

In [29]:
p_yes

0.007054673721340388

In [30]:
p_no

0.02742857142857143

In [31]:
def occourance(p_yes,p_no):
    print('Game Will Be Played') if p_yes>p_no else print('Game Will Not Be Played')

In [33]:
occourance(p_yes,p_no)

Game Will Not Be Played

In [34]:
from sklearn.naive_bayes import GaussianNB

In [35]:
gnb=GaussianNB()

In [37]:
new_df

,ohe1__outlook_Overcast,ohe1__outlook_Rain,ohe1__outlook_Sunny,ohe2__temp_Cool,ohe2__temp_Hot,ohe2__temp_Mild,ohe3__humidity_High,ohe3__humidity_Normal,ohe4__wind_Strong,ohe4__wind_Weak,remainder__play
0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0
1,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0
2,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1
3,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1
4,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1
5,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0
6,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1
7,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0
8,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1
9,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1
10,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1
11,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1
12,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1
13,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0

In [40]:
gnb.fit(new_df.drop(columns='remainder__play'),new_df['remainder__play'])

GaussianNB()

In [44]:
gnb.predict(np.array([0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0]).reshape(1,-1))

G:\anaconda\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

array([0])